# -*- coding: utf-8 -*-
"""FINAL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XFA0hUx-E8T3N-oFSg_aeQZZ-EiYJjJz

install required libraries
"""

!pip install pandas numpy scikit-learn nltk
!pip install matplotlib seaborn

"""Load the dataset"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
data = pd.read_csv('/content/Language Detection.csv.zip')
data.head()

data['Language'].value_counts()

"""Data cleaning and preprossing"""

import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r'\d+', '', text)          # remove numbers
    text = re.sub(r'[^\w\s]', '', text)      # remove punctuation
    text = re.sub(r'\s+', ' ', text)         # remove extra spaces
    return text.strip()

data['Text'] = data['Text'].apply(clean_text)

"""Encode labels"""

from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
data['Language_encoded'] = encoder.fit_transform(data['Language'])
#

"""Train_Test split"""

from sklearn.model_selection import train_test_split
x = data['Text']
y = data['Language_encoded']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42, stratify=y)

"""Feature Extractin"""

from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(
    analyzer='char',
    ngram_range=(2, 4)
)
x_train_vectorized = vectorizer.fit_transform(x_train)
x_test_vectorized = vectorizer.transform(x_test)
#

"""Train the model"""

from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)
model.fit(x_train_vectorized, y_train)
#

"""Evaluate the model"""

from sklearn.metrics import accuracy_score, classification_report
y_pred = model.predict(x_test_vectorized)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print(classification_report(y_test, y_pred, target_names=encoder.classes_))
#

"""Test wiyh custom input"""

def detect_language(text):
    text = clean_text(text)
    text_vec = vectorizer.transform([text])
    pred = model.predict(text_vec)
    return encoder.inverse_transform(pred)[0]

print(detect_language("This is a simple English sentence"))
print(detect_language("Je suis très heureux aujourd'hui"))
print(detect_language("நான் இன்று மகிழ்ச்சியாக இருக்கிறேன்"))
print(detect_language("Das ist ein deutscher Satz"))
print(detect_language("これは日本語の文章です"))
print(detect_language("سلام عليكم"))
print(detect_language("hi how areyou"))


#

import gradio as gr

def transcribe_audio(audio_file):
    # هنا تضع المنطق الخاص بك الموجود في الكولاب
    # text = your_model_prediction(audio_file)
    return "نص الكلام المستخرج"

demo = gr.Interface(
    fn=transcribe_audio,
    inputs=gr.Audio(type="filepath"), # Removed source="microphone"
    outputs="text",
    title="نظام التعرف على الكلام"
)

demo.launch(share=True)